name: Windows Go Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install TDM-GCC
      run: |
        $url = "https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe"
        Invoke-WebRequest -Uri $url -OutFile tdm-gcc-installer.exe
        Start-Process -FilePath .\tdm-gcc-installer.exe -Args "/S" -Wait
        Add-Content -Path $env:GITHUB_PATH -Value "C:\TDM-GCC-64\bin"

    - name: Verify GCC
      run: gcc --version
      
    - name: ini 末端
      run: go mod init github.com/zzxjz/demo-emulator
    
    # Go依赖安装
    - name: Install Go dependencies
      run: |
        go get github.com/go-gl/glfw/v3.3/glfw@latest
        go get github.com/go-gl/gl/v2.1/gl@latest

    - name: Build
      run: |
        go mod tidy
        go build -o demo-emulator.exe
      env:
        CGO_ENABLED: 1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-emulator-windows
        path: demo-emulator.exe
